builders:
  artemis:
    import: 'package:artemis/builder.dart'
    builder_factories: ['graphQLQueryBuilder']
    build_extensions: {'$lib$': ['.graphql.dart']}
    auto_apply: dependents
    build_to: source
    applies_builders: ['json_serializable']
    runs_before: ['json_serializable']
