name: artemis
version: 1.1.0

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

description: Build dart types from GraphQL schemas and queries (using Introspection Query).

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_config: ^1.0.0
  code_builder: ^4.1.0
  build: ^2.1.1
  collection: ^1.15.0
  dart_style: ^2.2.0
  equatable: ^2.0.3
  glob: ^2.0.2
  gql_dedupe_link: ^2.0.0
  gql_exec: ^1.0.0+1
  gql_http_link: ^1.0.0+1
  gql_link: ^1.0.0+1
  gql: ^1.0.0+1
  http: ^1.1.0
  json_annotation: ^4.4.0
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.2.0
  yaml: ^3.1.0
  graphql_code_builder_flutter:
#    git:
#      url: https://github.com/UnitedTraders/graphql_code_builder_flutter.git
#      ref: 1.0.5
    path: ../graphql_code_builder_flutter

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.5
  build_test: ^2.1.4
  json_serializable: ^6.1.1
  build_resolvers: ^2.0.5
  test: ^1.19.5
  logging: ^1.0.2
  lints: ^3.0.0
